# Generated by Django 4.2.1 on 2023-05-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_data_test", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("classroom_name", models.CharField(max_length=128)),
                ("building", models.CharField(max_length=128)),
                ("classroom_covered", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="LabelClassroom",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("classroom_id", models.IntegerField()),
                ("label_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Labeltable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label_name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Occupytable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classroom_id", models.IntegerField()),
                ("date", models.CharField(max_length=10)),
                ("time", models.CharField(max_length=10)),
                ("available", models.BooleanField()),
                ("covered", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
